backend:
  name: "github"
  auth_scope: "public_repo"
  # NOTE: branch is set programmatically in admin.astro
  repo: "brunoRoemers/jouer-bouger"
media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
local_backend: true
collections:
  - name: "cards"
    label: "Cards"
    folder: "src/content/cards"
    format: "yml"
    create: true
    slug: "{{slug}}"
    identifier_field: "slug"
    preview_path: "/{{filename}}"
    summary: "{{slug}} - {{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "slug"
        hint: "The slug cannot be edited once the page is published."
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Video URL"
        name: "videoUrl"
        widget: "string"
      - label: "Catégorie"
        name: "category"
        widget: "string"
        required: false
      - label: "Age"
        name: "age"
        widget: "string"
        required: false
      - label: "Lieu et Surface"
        name: "placeAndSurface"
        widget: "string"
        required: false
      - label: "Matériel"
        name: "materials"
        widget: "text"
        required: false
      - label: "Durée"
        name: "duration"
        widget: "string"
        required: false
      - label: "But du Jeu"
        name: "goal"
        widget: "text"
        required: false
      - label: "Pour Gagner"
        name: "victory"
        widget: "text"
        required: false
      - label: "Variantes a Deux"
        name: "variationTwoPlayers"
        widget: "text"
        required: false
      - label: "Variante à Plusieurs Joueurs"
        name: "variationManyPlayers"
        widget: "text"
        required: false